In [1]:
from scripts.test_haitem.feature_extraction import Extract_feature_from_segment
import pandas as pd
from pathlib import Path
from pyarrow.parquet import ParquetFile
import pyarrow as pa 

dataset_name = 'signal_dataset_haytem'
dataset_path = Path(f'data/datasets/{dataset_name}/cases/')

In [2]:
pf = ParquetFile(dataset_path / 'case0001.parquet') 
first_ten_rows = next(pf.iter_batches(batch_size = 10)) 
data = pa.Table.from_batches([first_ten_rows]).to_pandas()

In [3]:

def test_number_sup(str,max_time):
    if 'time' in str or 'label' in str:
        return True
    if '_' in str:
        number = str.split('_')[1]
        if int(number) < max_time:
            return True
        else:
            return False
    else:
        return True

data = data[[col for col in data.columns if test_number_sup(col,150)]] # on restreint les données à 5 minutes
data.head()

,bis_0,bis_1,bis_2,bis_3,bis_4,bis_5,bis_6,bis_7,bis_8,bis_9,...,sbp_146,sbp_147,sbp_148,sbp_149,label,time,intervention,time_before_IOH,label_id,caseid
0,40.900002,40.200001,39.800001,39.575001,39.320,39.116667,38.600,38.350,38.533333,38.670,...,145.70,145.35,144.90,145.85,1,00:22:48,False,454.0,1.0_1,1
1,38.900000,38.935294,38.972222,38.994737,38.870,38.680000,38.430,38.225,38.030000,38.025,...,143.25,142.95,142.55,141.15,1,00:23:18,False,424.0,1.0_1,1
2,37.605000,37.335000,36.990000,36.720000,36.460,36.015000,35.550,35.100,34.680000,34.410,...,134.15,133.75,133.40,133.05,1,00:23:48,False,394.0,1.0_1,1
3,32.485000,32.040000,31.640000,31.285000,31.110,30.985000,30.865,30.705,30.410000,30.150,...,130.20,130.05,129.65,129.50,1,00:24:18,False,364.0,1.0_1,1
4,29.295000,29.130000,29.015000,28.950000,28.835,28.705000,28.585,28.470,28.355000,28.240,...,129.45,129.40,129.30,129.30,1,00:24:48,False,334.0,1.0_1,1

In [4]:
segment = data.iloc[0].copy()
segment = pd.DataFrame(segment).T
extrator = Extract_feature_from_segment(segment)
features = extrator.extract_all_features()

print(features)

   mbp_1  mbp_2   ph   pd  bis_1  bis_2  sbp_1  sbp_2  dbp_1  dbp_2  ...  \
0    0.0    0.0  0.0  0.0  116.0  212.0    4.0    0.0    4.0    0.0  ...

   mbp_0_coef_2  mbp_0_intercept  mbp_1_coef_0  mbp_1_coef_1  mbp_1_coef_2  \
0     -0.036182        81.811436           0.0     -0.004248     -0.003372

   mbp_1_intercept  mbp_2_coef_0  mbp_2_coef_1  mbp_2_coef_2  mbp_2_intercept
0       108.644989           0.0      0.247182     -0.006989       108.994794

[1 rows x 48 columns]

/home/aubouinb/Nextcloud2/Code/hypotension_pred/.venv/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/aubouinb/Nextcloud2/Code/hypotension_pred/.venv/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/aubouinb/Nextcloud2/Code/hypotension_pred/.venv/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)